# config

site_name: Documentação do Composer
site_description: "Documentação do Composer [pt-br]"
docs_dir: doc
site_dir: build/1.10
use_directory_urls: false

# theme

theme:
    name: readthedocs
    custom_dir: theme/readthedocs
    prev_next_buttons_location: bottom
    static_templates:
        # config files
        - .nojekyll
        # templates
        - 404.html
        - pesquisar.html

# extensions

plugins:
    - search:
        lang: ['pt']

markdown_extensions:
    - attr_list
    - toc:
        permalink: true

# github

repo_url: https://github.com/adielcristo/composer-doc-pt-br
edit_uri: edit/1.10/doc/

# navigation

nav:
    - index.md
    - Livro:
        - introducao.md
        - uso-basico.md
        - bibliotecas.md
        - 'CLI / Comandos': cli.md
        - esquema.md
        - repositorios.md
        - config.md
        - comunidade.md
    - Artigos:
        - artigos/aliases.md
